string frame_id

int32 arm_side
int32 ARM_R = 1
int32 ARM_L = 2

ReachabilityRangeQuery[] queries

geometry_msgs/Pose T_B_W

float64 torso_q

float64[7] arm_q
bool arm_q_valid

---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
float64[] match_dist
